"use client";

import React from "react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="flex-1 bg-[#f8fafc] p-4 lg:p-8 max-w-[860px] mx-auto w-full space-y-6 text-slate-800">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-slate-900">
          Terms of Service
        </h1>
        <p className="text-xs text-slate-500 mt-1">
          Last updated: September 2026 (Draft for administrative review)
        </p>
      </div>

      <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-xs text-amber-800 space-y-1">
        <p className="font-semibold">Notice on Pilot Project Status</p>
        <p>
          WardAlert is a predictive intelligence research system developed for municipal pilot evaluation in Mumbai Ward G/South. This document represents a working operational draft.
        </p>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 p-6 space-y-6 text-xs leading-relaxed shadow-xs">
        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">1. Purpose and Operational Scope</h2>
          <p>
            WardAlert provides hyperlocal predictive modeling for municipal flood assessment in Mumbai Ward G/South. The platform evaluates rainfall series, elevation gradients, and drainage proximity to calculate flood probability and drainage gap signals.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">2. Public Data Sources and Attribution</h2>
          <p>
            The system consumes open datasets including Brihanmumbai Municipal Corporation (BMC) flood spot coordinates, OpenStreetMap drainage geometries, NASA SRTM digital elevation data, and CHIRPS/ERA5 meteorological reanalysis. All original data rights remain with their respective providers.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">3. Predictive Modeling Limitations</h2>
          <p>
            Predictions generated by Model A, Model B, and the residual delta metric are probabilistic estimates based on historical events and mathematical modeling. They are designed to assist municipal engineering decisions and do not guarantee the absence or presence of flooding during extreme weather events.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">4. Notification Services and Simulation</h2>
          <p>
            Alert broadcasts demonstrated through this interface are simulated for test evaluation unless connected to active municipal Twilio credentials. In simulated mode, no live SMS or WhatsApp messages are transmitted to phone numbers.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">5. Administrative Feedback and Contact</h2>
          <p>
            For questions regarding model assumptions, code provenance, or pilot deployments in additional wards, contact the WardAlert municipal engineering team.
          </p>
        </section>
      </div>

      <div className="text-center text-xs text-slate-400">
        <Link href="/" className="text-[#0066cc] hover:underline">Return to Dashboard</Link>
      </div>
    </div>
  );
}
