"use client";

import React from "react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="p-4 lg:p-6 space-y-4 max-w-4xl mx-auto w-full font-sans text-xs">
      <div className="p-4 bg-[#ffffff] border border-[#d4dae3] rounded-sm space-y-2">
        <div className="flex items-center justify-between">
          <div className="text-[10px] uppercase font-mono tracking-widest text-[#5b6478]">
            LEGAL TERMS OF SERVICE
          </div>
          <span className="px-1.5 py-0.5 bg-[#fffbeb] text-[#b45309] border border-[#fde68a] text-[10px] font-mono font-bold">
            DRAFT · REVIEW REQUIRED
          </span>
        </div>
        <h1 className="text-base font-bold text-[#1a1f2e] tracking-tight">
          WardAlert Operations Terms of Service
        </h1>
        <p className="text-[#5b6478] text-xs">
          Last Updated: September 2026 · MUSA CodeX 2026 Research Prototype
        </p>
      </div>

      <div className="p-5 bg-[#ffffff] border border-[#d4dae3] rounded-sm space-y-4 leading-relaxed text-[#1a1f2e]">
        <section className="space-y-1.5">
          <h2 className="text-xs font-bold uppercase font-mono tracking-wider text-[#1a1f2e]">
            1. Nature of the Service
          </h2>
          <p className="text-[#5b6478]">
            WardAlert is a civic research prototype developed for the MUSA CodeX 2026 hackathon. It provides hyperlocal flood risk predictions and cause-attribution telemetry for Mumbai Ward G-South (Worli, Lower Parel, Prabhadevi) based on historical rainfall datasets, municipal flood reports, and open GIS data.
          </p>
        </section>

        <section className="space-y-1.5">
          <h2 className="text-xs font-bold uppercase font-mono tracking-wider text-[#1a1f2e]">
            2. Operational Advisory & Disclaimer
          </h2>
          <p className="text-[#5b6478]">
            All predictions generated by Model A, Model B, and the residual Δ are statistical probability estimates produced by machine learning models (XGBoost). They are intended to support, not replace, formal municipal disaster management guidelines and official IMD or BMC emergency directives.
          </p>
        </section>

        <section className="space-y-1.5">
          <h2 className="text-xs font-bold uppercase font-mono tracking-wider text-[#1a1f2e]">
            3. Messaging & Telemetry Data
          </h2>
          <p className="text-[#5b6478]">
            Citizens who interact with the WhatsApp webhook or emergency broadcast services receive automated advisory messages. Standard cellular operator messaging terms may apply. Subscriptions expire automatically after 7 days unless renewed with the EXTEND command or cancelled via STOP.
          </p>
        </section>

        <section className="space-y-1.5">
          <h2 className="text-xs font-bold uppercase font-mono tracking-wider text-[#1a1f2e]">
            4. Open Public Data Sources
          </h2>
          <p className="text-[#5b6478]">
            Geospatial drainage geometries are derived from OpenStreetMap (ODbL). Rainfall observations originate from public CHIRPS and ERA5 precipitation reanalysis. Elevation data is sourced from NASA SRTM.
          </p>
        </section>
      </div>

      <div className="text-center pt-2">
        <Link href="/" className="text-xs font-mono text-[#1e40af] hover:underline">
          ← Return to Operational Map
        </Link>
      </div>
    </div>
  );
}
